services:
  app:
    build: .
    container_name: stocks_web
    ports:
      - "8092:80"
    volumes:
      - .:/var/www/html
      - ./data/uploads:/var/www/html/public/uploads
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - APP_URL=${APP_URL}
      - APP_DEBUG=${APP_DEBUG}
      - APP_KEY=${APP_KEY}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_ENCRYPTION=${SMTP_ENCRYPTION}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stocks.rule=Host(`stocks.leofranz.fr`)"
      - "traefik.http.routers.stocks.entrypoints=websecure"
      - "traefik.http.routers.stocks.tls.certresolver=le"
      - "traefik.http.services.stocks.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - db_internal
    restart: unless-stopped

networks:
  proxy:
    external: true
  db_internal:
    external: true
